/* globals exports: false, require: false */
/* eslint-disable camelcase */

const { src, dest, watch } = require( 'gulp' );
const csso = require( 'gulp-csso' );
const npm = require( 'npm' );
const babel = require( 'gulp-babel' );
const svgmin = require( 'gulp-svgmin' );
const { argv } = require( 'yargs' );
const htmlmin = require( 'gulp-htmlmin' );
const terser = require( 'gulp-terser' );
const PATHS = {
  JS: './src/**/*.js',
  CSS: './src/**/*.css',
  CSS_NOT: './src/**/_*.css',
  SVG: './src/**/*.svg',
  HTML: './src/**/*.html',
  DEST: './docs',
};

function build( shouldCompSCSS = true ) {
  if ( argv.production ) {
    minJS();
  }
  else {
    compJS();
  }
  minSvg();
  minHTML();

  if ( shouldCompSCSS ) {
    return compSCSS()
      .then( () => {
        minCSS();
      } );
  }
  return minCSS();
}

function buildWatch() {
  build()
    .then( () => {
      watch(
        [ PATHS.JS, PATHS.CSS, PATHS.SVG ],
        () => build( false )
      );
    } );
}

function minHTML() {
  return src( PATHS.HTML )
    .pipe( htmlmin( {
      collapseBooleanAttributes: true,
      collapseWhitespace: true,
      decodeEntities: true,
      html5: true,
      includeAutoGeneratedTags: true,
      quoteCharacter: '"',

      removeComments: true,
      removeRedundantAttributes: true,
      sortAttributes: true,
      sortClassName: true,
      trimCustomFragments: false,
      useShortDoctype: true,
    } ) )
    .pipe( dest( PATHS.DEST ) );
}

function compSCSS( cb ) {
  return new Promise( resolve => {
    npm.load( () => {
      npm.run(
        'sass',
        () => {
          if ( cb ) {
            cb();
          }
          resolve();
        }
      );
    } );
  } );
}

function compJS() {
  return src( PATHS.JS )
    .pipe( babel() )
    .pipe( dest( PATHS.DEST ) );
}

function minJS() {
  if ( argv.production ) {
    return src( PATHS.JS )
      .pipe( babel() )
      .pipe( terser( {
        // https://terser.org/docs/api-reference
        ecma: 2020,
        compress: {
          drop_console: true,
          keep_fargs: false,
          passes: 3,
        },
        format: {
          quote_style: 1,
        },
      } ) )
      .pipe( dest( PATHS.DEST ) );
  }
  return src( PATHS.JS )
    .pipe( babel() )
    .pipe( dest( PATHS.DEST ) );
}

function minCSS() {
  return src(
    PATHS.CSS,
    { ignore: PATHS.CSS_NOT }
  )
    .pipe( csso() )
    .pipe( dest( PATHS.DEST ) );
}

function minSvg() {
  return src( PATHS.SVG )
    .pipe( svgmin( {
      multipass: true,
      precision: 3,
      plugins: [
        {
          sortAttrs: {
            order: [
              'id',
              'width',
              'height',
              'x',
              'x1',
              'x2',
              'y',
              'y1',
              'y2',
              'cx',
              'cy',
              'r',
              'fill',
              'stroke',
              'marker',
              'd',
              'points',
            ],
          },
        },
        { removeScriptElement: true },
        { removeDimensions: true },
      ],
    } ) )
    .pipe( dest( PATHS.DEST ) );
}

exports.default = exports.build = build;
exports.minSvg = minSvg;
exports.minCSS = minCSS;
exports.compJS = compJS;
exports.minJS = minJS;
exports.compSCSS = compSCSS;
exports.minHTML = minHTML;

exports.build_watch = buildWatch;
