const { src, dest, watch, parallel } = require( 'gulp' );
const csso = require( 'gulp-csso' );
const babel = require( 'gulp-babel' );
const svgmin = require( 'gulp-svgmin' );
const { argv } = require( 'yargs' );
const htmlmin = require( 'gulp-htmlmin' );
const terser = require( 'gulp-terser' );
const sass = require( 'gulp-sass' );
const rename = require( 'gulp-rename' );
const sourcemaps = require( 'gulp-sourcemaps' );
sass.compiler = require( 'sass' );

const PATHS = {
  DEST: './docs',
  FAVICONS: [
    './src/**/favicon.min.svg',
    './src/**/favicon.ico',
    './src/**/favicon.png',
  ],
  HTML: [ './src/**/*.html' ],
  JS: [ './src/**/*.js' ],
  SCSS: [ './src/**/*.scss' ],
  SOURCEMAPS_DEST: './',
  SVG: [ './src/**/*.svg', '!./src/**/*.min.svg' ],
  SVG_DEST: './src',
};

const build = parallel(
  compJS,
  minSvg,
  minHTML,
  compSCSS
);

const start = parallel(
  build,
  watchFn
);

function watchFn() {
  watch(
    PATHS.JS,
    compJS
  );
  watch(
    PATHS.SCSS,
    compSCSS
  );
  watch(
    PATHS.HTML,
    minHTML
  );
  watch(
    PATHS.SVG,
    minSvg
  );
}
function minHTML() {
  return src( PATHS.HTML )
    .pipe( htmlmin( {
      collapseBooleanAttributes: true,
      collapseWhitespace: true,
      decodeEntities: true,
      html5: true,
      includeAutoGeneratedTags: true,
      quoteCharacter: '"',
      removeComments: true,
      removeRedundantAttributes: true,
      sortAttributes: true,
      sortClassName: true,
      trimCustomFragments: false,
      useShortDoctype: true,
    } ) )
    .pipe( dest( PATHS.DEST ) );
}

function compJS() {
  const progress = src( PATHS.JS )
    .pipe( sourcemaps.init() )

    .pipe( babel() );

  if ( argv.production ) {
    // https://terser.org/docs/api-reference
    progress.pipe( terser( {
      compress: {
        drop_console: true,
        keep_fargs: false,
        passes: 3,
      },
      ecma: 2020,
      format: {
        quote_style: 1,
      },
    } ) );
  }

  return progress
    .pipe( sourcemaps.write( PATHS.SOURCEMAPS_DEST ) )
    .pipe( dest( PATHS.DEST ) );
}

function compSCSS() {
  const progress = src( PATHS.SCSS )
    .pipe( sourcemaps.init() )

    .pipe( sass() );

  if ( argv.production ) {
    progress.pipe( csso() );
  }

  return progress
    .pipe( sourcemaps.write( PATHS.SOURCEMAPS_DEST ) )
    .pipe( dest( PATHS.DEST ) );
}

function minSvg() {
  src( PATHS.SVG )
    .pipe( svgmin( {
      multipass: true,
      plugins: [
        { sortAttrs: true },
        { removeScriptElement: true },
        { removeDimensions: true },
        { removeAttrs: { attrs: [ 'class' ] } },
      ],
      precision: 3,
    } ) )
    .pipe( rename( path => {
      path.extname = '.min.svg';
    } ) )
    .pipe( dest( PATHS.SVG_DEST ) );

  return src( PATHS.FAVICONS )
    .pipe( rename( path => {
      if ( path.basename.endsWith( '.min' ) ) {
        path.basename = path.basename.slice(
          0,
          -4
        );
      }
    } ) )
    .pipe( dest( PATHS.DEST ) );
}

exports.default = exports.build = build;
exports.minSvg = minSvg;
exports.compJS = compJS;
exports.compSCSS = compSCSS;
exports.minHTML = minHTML;

exports.start = start;
